# Generated by Django 5.0.6 on 2024-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_likes'),
        ('core', '0003_alter_user_profile_picture_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='blog.post'),
        ),
    ]
