# Generated by Django 5.0.6 on 2024-06-22 06:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blogs/thumbnail')),
                ('is_private', models.BooleanField(default=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Not request yet'), (1, 'Request for public'), (2, 'Approved post'), (3, 'Declined post')], default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
